Deleting messages from the list.
EnvironmentalDashboard/cwd-editor pull request #2
Opened 2020-06-08 14:15 UTC by adartulloch

This pull request is attempting to create an option to remove messages from "view" and "gauges". I do that by updating going to the DB and updating the message to an empty string and the probability to 0. However, there are a few bugs that I do not know how to fix. One is that when I call the onClick of the delete icon to remove the entry from the form, it does so, however it also gives me a console error. I suspect is has to do with how I am handling this:
```
var elem = document.getElementById("row");
    if (elem.parentNode) {
      elem.parentNode.removeChild(elem);
    }
```
which should be properly deleting one item from the form.

2020-06-08 18:01 UTC, Sammidysam requested changes
We need a backend route for deleting a message.  Before this can be merged, we will need to move a pull request through the backend project adding a delete route.  Then, we also need to delete using the React way, as that is what is currently causing the console error.

Nice work though!  I can see you learning by doing.

2020-06-08 18:33 UTC, adartulloch commented on src/MessageInput.js
> +    api.post(`glyphs/${this.state.id}/messages/${this.state.index}`,
I'm almost certain that the state should take care of it here...but I think I'll be able to tell if it doesn't.

2020-06-08 18:53 UTC, adartulloch commented
I'm looking through the backend code now, and I'm assuming that I will have to write methods in `glyphs.js` for a route to delete?

2020-06-08 18:53 UTC, Sammidysam commented on src/MessageInput.js
> +    api.post(`glyphs/${this.state.id}/messages/${this.state.index}`,
Certainly!  This is purely me just asking since I didn't bother checking myself.  Just something to keep in mind.

2020-06-08 18:55 UTC, Sammidysam commented
Yep.  Feel free to contact @acrap5 if you would like a call intro to everything - he did say he can find a time on Slack.  Otherwise, you'll want to mimic messages where you have a function that does similar logic on both gauges and views.

2020-06-08 19:10 UTC, adartulloch commented
Ok! I reached out to him and will proceed from here.
This is silly, but how do I create a pull request to a repository that I have commit access to? Do I still have to make a remote for the feature branch?

2020-06-08 19:19 UTC, Sammidysam commented
You should be able to do this process:
- On `master`
- `git checkout -b new-feature`
- `git push -u origin new-feature`
- Go to GitHub and click "New pull request"

Does that answer the question fine?

2020-06-16 20:09 UTC, Sammidysam commented
Hey, just wanted to check on this status of this because it has been a week?

2020-06-16 23:13 UTC, Sammidysam commented
Sorry for not being clear.  In particular, I am interested in if work has been done on the backend to accommodate this frontend.

2020-06-17 12:06 UTC, adartulloch commented
I moved to focus on CWD stuff before finishing the backend stuff up here as I thought Dashboard would be of a higher priority. What do you think?

2020-06-17 13:25 UTC, adartulloch commented
But I went ahead with the backend in the mean time, and opened a PR there.

2020-06-22 19:50 UTC, Sammidysam commented
Sounds great!  I got a chance to review that.  Could you also make the requested changes here that are irrelevant to the backend existing or not in the meantime?

2020-07-09 20:53 UTC, Sammidysam commented
@adartulloch Just checking in on this since my last comments were a week ago.

2020-07-14 14:50 UTC, adartulloch commented
Wow, I am so confused because this branch is missing both locally and on from `git branch -r`. I may open a new one...not quite sure what happened here. But I agree with the splicing, and I will get to it with the new backend routes that I believe should work

2020-07-14 14:54 UTC, adartulloch commented
Oh, I see what happened. I forgot that I had originally forked this branch.

2020-07-14 17:20 UTC, Sammidysam commented
So you're fine and all set to continue then?

2020-07-24 21:12 UTC, Sammidysam commented
@adartulloch Do you have pending changes here or should I finish it up?

2020-07-27 14:07 UTC, adartulloch commented
Didn't quite get a chance to finish up the React stuff!

2020-07-29 14:25 UTC, Sammidysam commented
Closing this since we are delaying the backend route to the fall, and therefore this cannot work until the backend is working.  I hope Adar does not delete his fork in the meantime, because this branch looks basically done, but I would say using the `delete` method is still a bit weird just given that it's not used much.  Maybe the opinion there will change over time, though.

2020-07-29 14:25 UTC, closed without merging